<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ItSkillMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $country = [
            '1' => ['Overall project management', 'プロジェクト全体の管理', 0],
            '2' => ['Member management', 'メンバーマネジメント', 0],
            '3' => ['Requirments definition', '要件定義', 0],
            '4' => ['Basic design', '基本設計', 0],
            '5' => ['Detail design', '詳細設計', 0],
            '6' => ['Development and Implementation', '開発・実装', 0],
            '7' => ['Tests', 'テスト', 0],
            '8' => ['Maintenance and Operation', '保守・運用', 0],
            '9' => ['Data analysis', 'データ解析', 0],
            '10' => ['Network build-up and organization', 'ネットワーク設計・構築', 1],
            '11' => ['Network maintenance and operation', 'ネットワーク運用・保守', 1],
            '12' => ['Server build-up and organization', 'サーバー設計・構築', 1],
            '13' => ['Server maintenance and operation', 'サーバー運用・保守', 1],
            '14' => ['Database build-up and organization', 'データベース設計・構築', 1],
            '15' => ['Database tuning', 'データベースチューニング', 1],
            '16' => ['Database maintenance and operation', 'データベース運用・保守', 1],
            '17' => ['Windows', 'Windows', 2],
            '18' => ['MacOS', 'MacOS', 2],
            '19' => ['Linux', 'Linux', 2],
            '20' => ['AIX', 'AIX', 2],
            '21' => ['HP-UX', 'HP-UX', 2],
            '22' => ['Solaris', 'Solaris', 2],
            '23' => ['BSD', 'BSD', 2],
            '24' => ['Others', 'Others', 2],
            '25' => ['C', 'C', 3],
            '26' => ['C++', 'C++', 3],
            '27' => ['C#', 'C#', 3],
            '28' => ['Objective-C', 'Objective-C', 3],
            '29' => ['shell(C・B・K)', 'shell(C・B・K)', 3],
            '30' => ['HTML5', 'HTML5', 3],
            '31' => ['JavaScript', 'JavaScript', 3],
            '32' => ['VBA', 'VBA', 3],
            '33' => ['VisualBasic', 'VisualBasic', 3],
            '34' => ['VisualC', 'VisualC', 3],
            '35' => ['VisualC++', 'VisualC++', 3],
            '36' => ['VisualJ#', 'VisualJ#', 3],
            '37' => ['ASP', 'ASP', 3],
            '38' => ['Visual Basic .NET', 'Visual Basic .NET', 3],
            '39' => ['Visual C# .NET', 'Visual C# .NET', 3],
            '40' => ['Visual C++ .NET', 'Visual C++ .NET', 3],
            '41' => ['Visual J# .NET', 'Visual J# .NET', 3],
            '42' => ['ASP.NET', 'ASP.NET', 3],
            '43' => ['Delphi', 'Delphi', 3],
            '44' => ['SQL', 'SQL', 3],
            '45' => ['Perl', 'Perl', 3],
            '46' => ['PHP', 'PHP', 3],
            '47' => ['Ruby', 'Ruby', 3],
            '48' => ['Coldfusion', 'Coldfusion', 3],
            '49' => ['Java', 'Java', 3],
            '50' => ['J2EE・J2SE・J2ME', 'J2EE・J2SE・J2ME', 3],
            '51' => ['JSP', 'JSP', 3],
            '52' => ['EJB・JavaBeans', 'EJB・JavaBeans', 3],
            '53' => ['XML', 'XML', 3],
            '54' => ['Flash', 'Flash', 3],
            '55' => ['ABAP/4', 'ABAP/4', 3],
            '56' => ['COBOL', 'COBOL', 3],
            '57' => ['PL/1', 'PL/1', 3],
            '58' => ['RPG', 'RPG', 3],
            '59' => ['Assembler', 'アセンブラ', 3],
            '60' => ['Python', 'Python', 3],
            '61' => ['Swift', 'Swift', 3],
            '62' => ['Scala', 'Scala', 3],
            '63' => ['Go', 'Go', 3],
            '64' => ['R', 'R', 3],
            '65' => ['Dart', 'Dart', 3],
            '66' => ['Oracle', 'Oracle', 4],
            '67' => ['DB2', 'DB2', 4],
            '68' => ['Sybase', 'Sybase', 4],
            '69' => ['SQLServer', 'SQLServer', 4],
            '70' => ['Access', 'Access', 4],
            '71' => ['Notes・Domino', 'Notes・Domino', 4],
            '72' => ['Exchange', 'Exchange', 4],
            '73' => ['MYSQL', 'MYSQL', 4],
            '74' => ['PostgreSQL', 'PostgreSQL', 4],
            '75' => ['Finance/Accounting', '財務・会計', 5],
            '76' => ['HR/Payroll/Social insurance', '人事・給与・労務', 5],
            '77' => ['Manufacturing', '生産', 5],
            '78' => ['Sales', '販売', 5],
            '79' => ['Logistics', '物流', 5],
            '80' => ['Wholesale/Retail', '流通・小売', 5],
            '81' => ['Govermental or municipal offices/Public organizations', '官公庁・公共機関', 5],
            '82' => ['Medical fields', '医療業界', 5],
            '83' => ['Financial fields', '金融業界', 5],
            '84' => ['Communication fields', '通信業界', 5],
            '85' => ['Website development', 'Webサイト開発', 5],
            '86' => ['iOS development', 'iOS開発', 5],
            '87' => ['Android development', 'Android開発', 5],
            '88' => ['Play Framework', 'Play Framework', 6],
            '89' => ['Struts', 'Struts', 6],
            '90' => ['Struts2', 'Struts2', 6],
            '91' => ['Seasar', 'Seasar', 6],
            '92' => ['Slim3', 'Slim3', 6],
            '93' => ['Symfony', 'Symfony', 6],
            '94' => ['CakePHP', 'CakePHP', 6],
            '95' => ['CodeIgniter', 'CodeIgniter', 6],
            '96' => ['Zend Framework', 'Zend Framework', 6],
            '97' => ['FuelPHP', 'FuelPHP', 6],
            '98' => ['Ruby on Rails', 'Ruby on Rails', 6],
            '99' => ['Sinatra', 'Sinatra', 6],
            '100' => ['Catalyst', 'Catalyst', 6],
            '101' => ['Mojolicious', 'Mojolicious', 6],
            '102' => ['Django', 'Django', 6],
            '103' => ['CoffeeScript', 'CoffeeScript', 6],
            '104' => ['jQuery', 'jQuery', 6],
            '105' => ['Backborn.js', 'Backborn.js', 6],
            '106' => ['Node.js', 'Node.js', 6],
            '107' => ['cocos2d', 'cocos2d', 6],
            '108' => ['Unity', 'Unity', 6],
            '109' => ['Corona', 'Corona', 6],
            '110' => ['PhoneGap', 'PhoneGap', 6],
            '111' => ['Titanium Mobile', 'Titanium Mobile', 6],
            '112' => ['jQuery Mobile', 'jQuery Mobile', 6],
            '113' => ['jQTouch', 'jQTouch', 6],
            '114' => ['React', 'React', 6],
            '115' => ['AngularJS', 'AngularJS', 6],
            '116' => ['Hadoop', 'Hadoop', 6],
            '999' => ['Other', 'その他', 99],
        ];

        foreach ($country as $id => $name) {
                DB::table('it_skill_masters')->insert([
                'id' => $id,
                'skill_en_name' => $name[0],
                'skill_jp_name' => $name[1],
                'skill_cate_master_id' => $name[2],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
